# Generated by Django 4.2.6 on 2023-11-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobiles_pictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiles',
            old_name='pictures',
            new_name='picture',
        ),
    ]
